# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: product_management_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - product_management

  nginx:
    image: nginx:alpine
    container_name: product_management_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - product_management

  db:
    image: mysql:8.0
    container_name: product_management_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - product_management

  redis:
    image: redis:alpine
    container_name: product_management_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - product_management

networks:
  product_management:
    driver: bridge

volumes:
  dbdata: